spring:
  application:
    name: Argonia RPG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver